# .github/workflows/reuse_workflow.yml
name: Reuse Python Workflow from Template

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  # Reference the reusable workflow here at the top level of 'jobs'
    - name: Use Workflow Template
      uses: akashsinghx/repo1/.github/workflows/main.yml@main
