# .github/workflows/reuse_workflow.yml
name: Reuse Python Workflow from Template

on:
  push:
    branches:
      - main

jobs:
  call-workflow-A:
    uses: akashsinghx/repo1/.github/workflows/main.yml@main
    with:
      config-path: .github/main.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
