# .github/workflows/reuse_workflow.yml
name: Reuse Python Workflow from Template

on:
  push:
    branches:
      - main

jobs:
  call-workflow-A:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Workflow A
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await octokit.rest.actions.createWorkflowDispatch({
            owner: 'akashsinghx',  // Replace with the owner of repo1
            repo: 'repo1',         // Replace with the name of repo1
            workflow_id: 'main.yml',  // Replace with the name of the workflow file
            ref: 'main',           // Replace with the branch where the workflow is defined
            inputs: {
              config-path: '.github/main.yml'
            }
          });
          console.log(response);
